name: Flutter Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter doctor
      - run: flutter pub get
      - run: flutter build web
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v2
        with:
            name: web_upload
            path: build/web/
